modLoader = "kotlinforforge"
loaderVersion = "[5,)"
license = "WTFNMFPL"
issueTrackerURL = "${issuesUrl}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "fopwoc"
description = "Kotlin New Horizons — a Jetpack Compose runtime for Minecraft mods. And more."
displayURL = "${repositoryUrl}"

[[dependencies.${modId}]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5,)"
side = "BOTH"

[[dependencies.${modId}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion}]"
side = "BOTH"
