package io.github.fopwoc.knhmp

import java.io.File
import org.gradle.api.Project

/**
 * Mod identity is declared once (`gradle.properties` / the `knhmp` extension) and projected into
 * code and resources: a `ModMetadata` constants object generated into the shared root source sets,
 * and `${modId}`/`${modName}`/`${modVersion}`/`${minecraftVersion}`/`${repositoryUrl}`/`${issuesUrl}`
 * placeholders expanded in the loader metadata files of every island node.
 */
internal object KnhMpModMetadata {
    val METADATA_FILES = listOf("mcmod.info", "fabric.mod.json", "META-INF/mods.toml", "META-INF/neoforge.mods.toml")

    /** Under `.knhmp` like all generated state, so `clean` cannot remove it between configuration and a nested build. */
    fun generatedSourceRoot(project: Project): File = project.projectDir.resolve(".knhmp/generated/kotlin")

    fun generate(project: Project, extension: KnhMpExtension) {
        val file = generatedSourceRoot(project).resolve(extension.modGroup.replace('.', '/')).resolve("ModMetadata.kt")
        val content = """
            // Generated by KnhMP from the module's mod identity. Do not edit.
            package ${extension.modGroup}

            object ModMetadata {
                const val MOD_ID: String = "${extension.modId.kotlinEscaped()}"
                const val MOD_NAME: String = "${extension.modName.kotlinEscaped()}"
                const val MOD_VERSION: String = "${extension.modVersion.kotlinEscaped()}"
                const val MOD_GROUP: String = "${extension.modGroup.kotlinEscaped()}"
                const val KOTLIN_API_VERSION: String = "${(extension.minimumKotlinApiVersion() ?: "unknown").kotlinEscaped()}"
            }
        """.trimIndent() + "\n"
        file.parentFile.mkdirs()
        if (!file.exists() || file.readText() != content) file.writeText(content)
    }

    fun expansionProperties(extension: KnhMpExtension, minecraftVersion: String?): Map<String, String> = buildMap {
        put("modId", extension.modId)
        put("modName", extension.modName)
        put("modVersion", extension.modVersion)
        put("repositoryUrl", extension.repositoryUrl)
        put("issuesUrl", extension.repositoryUrl.takeIf(String::isNotEmpty)?.let { "$it/issues" }.orEmpty())
        minecraftVersion?.let { put("minecraftVersion", it) }
    }

    private fun String.kotlinEscaped(): String = replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
}

/** Java source roots of a logical source set (mixins are Java); only the directory itself. */
internal fun Project.javaSourceRoot(sourceSet: String): File = projectDir.resolve("src/$sourceSet/java")

/** Kotlin source roots of a logical source set: its directory plus generated code for shared roots. */
internal fun Project.kotlinSourceRoots(extension: KnhMpExtension, sourceSet: String): List<File> {
    val roots = extension.sourceSets.all().filter { it.parents().isEmpty() }.map { it.name() }
    return listOfNotNull(
        projectDir.resolve("src/$sourceSet/kotlin"),
        KnhMpModMetadata.generatedSourceRoot(this).takeIf { sourceSet in roots },
    )
}
