package io.github.fopwoc.knhmp

import org.gradle.api.Project

/**
 * GTNH 1.7.10 through GTNHGradle. The settings convention plugin is required by the GTNH
 * toolchain; its version follows the declared `com.gtnewhorizons.gtnhconvention` build plugin,
 * which ships in the same artifact. Minecraft/Forge/mapping coordinates are fixed by the GTNH
 * toolchain and live in the island's `gradle.properties`.
 */
internal class KnhMpGtnhIsland(module: Project, extension: KnhMpExtension, target: KnhMpTarget) :
    KnhMpIsland(module, extension, target, "gtnh") {

    override val nodes: List<KnhMpIslandNode> = singleNode(extension, target)

    /** RFG's `jar` is the MCP-named dev jar; `reobfJar` overwrites the plain name with the shipped one. */
    override fun devJar(node: KnhMpIslandNode) = jar(node).resolveSibling(jar(node).name.replace(".jar", "-dev.jar"))

    override fun generate() {
        val node = nodes.single()
        val conventionVersion = requirePluginVersion(node, CONVENTION_PLUGIN, "libs.plugins.gtnh.convention")
        writeGenerated("settings.gradle.kts", settingsScript(conventionVersion))
        writeGenerated("gradle.properties", propertiesFile(node))
        writeGenerated("build.gradle.kts", buildScript(node))
        // GTNHGradle validates `modGroup` and `mixinsPackage` as directories under the project's own
        // src/main/{java,kotlin}; the leaf's roots are linked there (an earlier generated placeholder
        // tree without files is replaced). The source sets themselves still mount the whole closure.
        val javaLink = directory.resolve("src/main/java")
        if (javaLink.isDirectory && !java.nio.file.Files.isSymbolicLink(javaLink.toPath()) && javaLink.walkTopDown().none { it.isFile }) {
            javaLink.deleteRecursively()
        }
        ensureSymbolicLink(javaLink, module.javaSourceRoot(node.sourceSet))
        ensureSymbolicLink(directory.resolve("src/main/kotlin"), module.projectDir.resolve("src/${node.sourceSet}/kotlin"))
    }

    private fun settingsScript(conventionVersion: String): String = """
        $HEADER
        ${settingsPluginManagement("https://nexus.gtnewhorizons.com/repository/public/").indent(8)}

        plugins {
            id("$SETTINGS_PLUGIN") version "${conventionVersion.escape()}"
            id("org.gradle.toolchains.foojay-resolver-convention") version "$FOOJAY_VERSION"
        }

        rootProject.name = "$buildName"
    """.trimIndent() + "\n"

    /**
     * GTNHGradle owns the 1.7.10 mixin pipeline: with `usesMixins` it adds UniMixins, runs the
     * annotation processor, generates `mixins.<modId>.json` from `mixinsPackage` (relative to
     * `modGroup`) and writes the `MixinConfigs` manifest entry. Access transformers are file names
     * under `META-INF` of the resources.
     */
    private fun mixinProperties(node: KnhMpIslandNode): String {
        val mixins = mixinsOf(node)
        val lines = mutableListOf<String>()
        if (mixins != null) {
            val prefix = "${extension.modGroup}."
            val packageName = checkNotNull(mixins.packageName)
            check(packageName.startsWith(prefix)) { "GTNHGradle requires the mixin package below modGroup ${extension.modGroup}: $packageName" }
            lines += "usesMixins = true"
            lines += "mixinsPackage = ${packageName.removePrefix(prefix)}"
            mixins.plugin?.let { lines += "mixinPlugin = ${it.removePrefix(prefix)}" }
            if (mixins.debug) lines += "usesMixinDebug = true"
        }
        val transformers = node.configuration.accessTransformers.map { it.removePrefix("META-INF/") }
        if (transformers.isNotEmpty()) lines += "accessTransformersFile = ${transformers.joinToString(" ")}"
        return lines.joinToString("\n")
    }

    private fun propertiesFile(node: KnhMpIslandNode): String = """
        # Generated by KnhMP. GTNHGradle reads its configuration from project properties.
        modName = ${extension.modName}
        modId = ${extension.modId}
        modGroup = ${extension.modGroup}
        modVersion = ${extension.modVersion}
        useModGroupForPublishing = true
        autoUpdateBuildScript = false
        gtnh.modules.gitVersion = false
        gtnh.modules.toolchain = true
        gtnh.modules.modernJava = true
        gtnh.modules.ideIntegration = false
        gtnh.modules.codeStyle = false
        forceToolchainVersion = ${extension.javaToolchain}
        enableModernJavaSyntax = modern
        versionPattern = [0-9]+\.[0-9]+\.[0-9]+
        minecraftVersion = 1.7.10
        forgeVersion = 10.13.4.1614
        channel = stable
        mappingsVersion = 12
        remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
        enableGenericInjection = true
        usesMavenPublishing = false
        org.gradle.configuration-cache = false
        ${mixinProperties(node).indent(8)}
    """.trimIndent() + "\n"

    private fun buildScript(node: KnhMpIslandNode): String {
        // GTNHGradle's settings convention already puts its own Kotlin Gradle plugin on the classpath and
        // owns the Java toolchain, so this island cannot pin either; the DSL cannot override them here.
        check(node.configuration.plugin(KOTLIN_PLUGIN) == null) {
            "Target gtnh cannot select a Kotlin Gradle plugin version; GTNHGradle ${requirePluginVersion(node, CONVENTION_PLUGIN, "")} provides it"
        }
        val plugins = listOf(pluginLine(KOTLIN_PLUGIN, null), pluginLine(CONVENTION_PLUGIN, null)) +
            declaredPluginLines(node, KOTLIN_PLUGIN, CONVENTION_PLUGIN)
        return """
            $HEADER
            ${SCRIPT_IMPORTS.indent(12)}

            plugins {
            ${plugins.block(4, 12)}
            }

            ${compilerScriptLines(node).block(0, 12)}

            group = "${extension.modGroup.escape()}"
            version = "${extension.modVersion.escape()}"

            base { archivesName.set("${archiveBaseName(node).escape()}") }

            repositories {
                maven("https://nexus.gtnewhorizons.com/repository/public/")
                maven("https://nexus.gtnewhorizons.com/repository/releases/")
                maven("https://nexus.gtnewhorizons.com/repository/central-sonatype-snapshots/")
                mavenCentral()
                google()
            }

            dependencies {
            ${dependencyLines(node).block(4, 12)}
            ${testDependencyLines(node).block(4, 12)}
            }

            kotlin {
                sourceSets.named("main") {
            ${sourceMountLines(node, includeLeaf = true).block(8, 12)}
                }
            }
            ${javaMountScript(node, includeLeaf = true).indent(12)}
            ${testMountScript(node).indent(12)}

            ${jvmTargetScript(node).indent(12)}

            ${kotlinRuntimeScript(node, FORGELIN_PROVIDED).indent(12)}

            tasks.named("reobfJar") { dependsOn("test") }
            // Forge classes loaded by tests write logs and configs into the working directory.
            tasks.withType<Test>().configureEach {
                val testWorkDirectory = layout.buildDirectory.dir("test-work")
                doFirst { testWorkDirectory.get().asFile.mkdirs() }
                workingDir = testWorkDirectory.get().asFile
            }

            ${resourceExpansionScript(node).indent(12)}

            ${exportTaskScript(listOf("tasks.named(\"packagePatchedMc\").map { layout.buildDirectory.file(\"rfg/recompiled_minecraft-1.7.10.jar\") }")).indent(12)}
        """.trimIndent() + "\n"
    }

    companion object {
        const val CONVENTION_PLUGIN = "com.gtnewhorizons.gtnhconvention"
        private const val SETTINGS_PLUGIN = "com.gtnewhorizons.gtnhsettingsconvention"

        /** GTNH's Kotlin runtime is Forgelin, which shades coroutines; a second copy must never load. */
        private val FORGELIN_PROVIDED = listOf(
            "org.jetbrains.kotlinx" to "kotlinx-coroutines-core",
            "org.jetbrains.kotlinx" to "kotlinx-coroutines-core-jvm",
            "org.jetbrains.kotlinx" to "kotlinx-coroutines-bom",
        )
    }
}
