modName = Test GUI
modId = testgui
modGroup = io.github.fopwoc.mods.testgui
useModGroupForPublishing = true
autoUpdateBuildScript = false
gtnh.modules.gitVersion = true
gtnh.modules.toolchain = false
gtnh.modules.modernJava = false
gtnh.modules.ideIntegration = false
versionPattern = [0-9]+\\.[0-9]+\\.[0-9]+
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
enableGenericInjection = true
usesMavenPublishing = false

org.gradle.configuration-cache = false
org.gradle.parallel = false
