[versions]
java = "25"
jvmBytecode = "8"
kotlin = "2.0.0"
forgelin = "2.0.3-GTNH"
serialization = "1.7.1"
compose = "1.6.11"
coroutines = "1.8.1"

[libraries]
forgelin = { module = "com.github.GTNewHorizons:Forgelin", version.ref = "forgelin" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
gtnh-convention = { id = "com.gtnewhorizons.gtnhconvention" }
buildconfig = { id = "com.github.gmazzo.buildconfig" }

